# catppuccin (mocha)
foreground = #cdd6f4
background = #1e1e2e
base00 = #11111b
base01 = #181825
base02 = #1e1e2e
base03 = #313244
base04 = #45475a
base05 = #585b70
base06 = #a6adc8
base07 = #bac2de
base08 = #f38ba8
base09 = #fab387
base0A = #f9e2af
base0B = #a6e3a1
base0C = #89dceb
base0D = #89b4fa
base0E = #cba6f7
base0F = #f5e0dc

tab_bar_bg = #11111b
tab_button_bg = #1e1e2e
tab_button_fg = #bac2de
tab_button_hover_bg = #313244
tab_button_hover_fg = #cdd6f4
tab_active_bg = #1e1e2e
tab_active_fg = #cba6f7
tab_active_border = #cba6f7
right_section_accent = #cba6f7
clock_fg = #cdd6f4
history_button_fg = #cdd6f4
history_button_active_bg = #45475a
zoom_label_fg = #cdd6f4
