# gruvbox dark
foreground = #ebdbb2
background = #282828
base00 = #1d2021
base01 = #282828
base02 = #3c3836
base03 = #504945
base04 = #665c54
base05 = #bdae93
base06 = #d5c4a1
base07 = #ebdbb2
base08 = #cc241d
base09 = #d65d0e
base0A = #d79921
base0B = #98971a
base0C = #689d6a
base0D = #458588
base0E = #b16286
base0F = #a89984

tab_bar_bg = #1d2021
tab_button_bg = #282828
tab_button_fg = #bdae93
tab_button_hover_bg = #3c3836
tab_button_hover_fg = #ebdbb2
tab_active_bg = #282828
tab_active_fg = #d79921
tab_active_border = #d79921
right_section_accent = #d79921
clock_fg = #ebdbb2
history_button_fg = #ebdbb2
history_button_active_bg = #504945
zoom_label_fg = #ebdbb2
