# tokyo-night
foreground = #c0caf5
background = #1a1b26
base00 = #15161e
base01 = #1a1b26
base02 = #292e42
base03 = #414868
base04 = #565f89
base05 = #9aa5ce
base06 = #cfc9c2
base07 = #c0caf5
base08 = #f7768e
base09 = #ff9e64
base0A = #e0af68
base0B = #9ece6a
base0C = #7dcfff
base0D = #7aa2f7
base0E = #bb9af7
base0F = #a9b1d6

tab_bar_bg = #15161e
tab_button_bg = #1a1b26
tab_button_fg = #9aa5ce
tab_button_hover_bg = #292e42
tab_button_hover_fg = #c0caf5
tab_active_bg = #1a1b26
tab_active_fg = #7aa2f7
tab_active_border = #7aa2f7
right_section_accent = #7aa2f7
clock_fg = #c0caf5
history_button_fg = #c0caf5
history_button_active_bg = #414868
zoom_label_fg = #c0caf5
